### ISSUE TITLE
PiCar-S Dragit issue

### ISSUE THREAD

**Issue by xlrirs** [sunfounder/SunFounder_Dragit#2]
Dragit can be used from the localhost. I am using a RaspberryPi 3 B+

In Dragit I am able to see the status of Raspberry Pi and the sensors.

Car is not moving and servo is not moving from the commands sent through Dragit. Dragit server is receiving the requests.

Outputs of the sprite is certain times in the form of html error.

Errors:
pi@picars:/opt/SunFounder_Dragit/Dragit $ sudo ./start
Server running
Performing system checks...

No module named cv2
Init GPIO17 success
Init GPIO18 success
Init GPIO27 success
Init GPIO22 success
Init GPIO23 success
Init GPIO24 success
Init GPIO25 success
Init GPIO4 success
Init GPIO5 success
Init GPIO6 success
Init GPIO13 success
Init GPIO19 success
Init GPIO26 success
Init GPIO12 success
Init GPIO16 success
Init GPIO20 success
Init GPIO21 success
an integer is required
No module named pismart.pismart
System check identified no issues (0 silenced).
September 13, 2018 - 15:48:02
Django version 1.11.15, using settings 'Dragit.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[13/Sep/2018 15:49:03] "GET / HTTP/1.1" 200 2339
Raspberry Pi run function start.
Get action: i2cdetect
Get value0: 1
Commands "ls /dev/i2c-1" output:
/dev/i2c-1
I2C device setup OK
i2cdetect output:
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- 48 -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --                        
Conneceted i2c device:
result: 0x40,0x48,0x70
[13/Sep/2018 15:49:14] "GET /run/raspberry_pi/?action=i2cdetect&value0=1 HTTP/1.1" 200 14

Get action: device_status
[13/Sep/2018 15:53:36] "GET /run/picar-s/?action=device_status HTTP/1.1" 200 23
Get action

[13/Sep/2018 15:53:43] "GET /run/picar-s/?action=device_status HTTP/1.1" 200 23
Get action: rw_run
Get value0: both
Get value1: forward
Get value2: 30
[13/Sep/2018 15:54:32] "GET /run/picar-s/?action=rw_run&value0=both&value1=forward&value2=30 HTTP/1.1" 200 56
Get action: rw_stop
[13/Sep/2018 15:54:32] "GET /run/picar-s/?action=rw_stop HTTP/1.1" 200 56

Get action: light_follower_analog
Internal Server Error: /run/modules/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 755, in run
    return HttpResponse(get_result(request))
  File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 571, in get_result
    result  = light_analog_index(channel)
  File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 83, in light_analog_index
    adc  = ADC(0x40)
  File "/opt/SunFounder_Dragit/Dragit/Dragit/libs/modules/PCF8591.py", line 35, in __init__
    self.bus = smbus.SMBus(self._bus_number)
TypeError: an integer is required

**Comment by sunfounder** [comment]
Hi 

Thanks for contacting us,

This is the compatibility problem of pi3 B+. It is expected to be fixed on Monday.And then I will reply you.
Hope your kind understanding.
Thanks



Best Regards
Jake 

support@sunfounder.com
 
From: xlrirs
Date: 2018-09-14 14:33
To: sunfounder/SunFounder_Dragit
CC: Subscribed
Subject: [sunfounder/SunFounder_Dragit] PiCar-S Dragit issue (#2)
Dragit can be used from the localhost. I am using a RaspberryPi 3 B+
In Dragit I am able to see the status of Raspberry Pi and the sensors.
Car is not moving and servo is not moving from the commands sent through Dragit. Dragit server is receiving the requests.
Outputs of the sprite is certain times in the form of html error.
Errors:
pi@picars:/opt/SunFounder_Dragit/Dragit $ sudo ./start
Server running
Performing system checks...
No module named cv2
Init GPIO17 success
Init GPIO18 success
Init GPIO27 success
Init GPIO22 success
Init GPIO23 success
Init GPIO24 success
Init GPIO25 success
Init GPIO4 success
Init GPIO5 success
Init GPIO6 success
Init GPIO13 success
Init GPIO19 success
Init GPIO26 success
Init GPIO12 success
Init GPIO16 success
Init GPIO20 success
Init GPIO21 success
an integer is required
No module named pismart.pismart
System check identified no issues (0 silenced).
September 13, 2018 - 15:48:02
Django version 1.11.15, using settings 'Dragit.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[13/Sep/2018 15:49:03] "GET / HTTP/1.1" 200 2339
Raspberry Pi run function start.
Get action: i2cdetect
Get value0: 1
Commands "ls /dev/i2c-1" output:
/dev/i2c-1
I2C device setup OK
i2cdetect output:
0 1 2 3 4 5 6 7 8 9 a b c d e f
00: -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- 48 -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: 70 -- -- -- -- -- -- --
Conneceted i2c device:
result: 0x40,0x48,0x70
[13/Sep/2018 15:49:14] "GET /run/raspberry_pi/?action=i2cdetect&value0=1 HTTP/1.1" 200 14
Get action: device_status
[13/Sep/2018 15:53:36] "GET /run/picar-s/?action=device_status HTTP/1.1" 200 23
Get action
[13/Sep/2018 15:53:43] "GET /run/picar-s/?action=device_status HTTP/1.1" 200 23
Get action: rw_run
Get value0: both
Get value1: forward
Get value2: 30
[13/Sep/2018 15:54:32] "GET /run/picar-s/?action=rw_run&value0=both&value1=forward&value2=30 HTTP/1.1" 200 56
Get action: rw_stop
[13/Sep/2018 15:54:32] "GET /run/picar-s/?action=rw_stop HTTP/1.1" 200 56
Get action: light_follower_analog
Internal Server Error: /run/modules/
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 755, in run
return HttpResponse(get_result(request))
File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 571, in get_result
result = light_analog_index(channel)
File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 83, in light_analog_index
adc = ADC(0x40)
File "/opt/SunFounder_Dragit/Dragit/Dragit/libs/modules/PCF8591.py", line 35, in init
self.bus = smbus.SMBus(self._bus_number)
TypeError: an integer is required
