### ISSUE TITLE
Can't start Dragit on PiCarV V2

### ISSUE THREAD

**Issue by krilleke** [sunfounder/SunFounder_Dragit#3]
I'm using the PiCarV V2 with RaspberryPi 1B+, getting this issue:

pi@raspberrypi:/opt/SunFounder_Dragit/Dragit $ sudo ./start
Server running
Performing system checks...

DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
Init GPIO17 success
Init GPIO18 success
Init GPIO27 success
Init GPIO22 success
Init GPIO23 success
Init GPIO24 success
Init GPIO25 success
Init GPIO4 success
Init GPIO5 success
Init GPIO6 success
Init GPIO13 success
Init GPIO19 success
Init GPIO26 success
Init GPIO12 success
Init GPIO16 success
Init GPIO20 success
Init GPIO21 success
DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
No module named pismart.pismart
Unhandled exception in thread started by <function wrapper at 0xb5dbdab0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/SunFounder_Dragit/Dragit/Dragit/urls.py", line 22, in <module>
    from modules import views as modules_views
  File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 25, in <module>
    from Dragit.libs.modules.rpi_time import DS1302 as DS1302
  File "/opt/SunFounder_Dragit/Dragit/Dragit/libs/modules/rpi_time.py", line 3, in <module>
    import ds1302
ImportError: libwiringPi.so: cannot open shared object file: No such file or directory

What is wrong?
Best Regards

**Comment by sunfounder** [comment]
Hi krilleke

Thanks for contacting us,your problem I have asked our technical team help

Any result ,I will reply you in time thanks



Best Regards
Jake 

support@sunfounder.com
 
From: krilleke
Date: 2018-09-24 00:20
To: sunfounder/SunFounder_Dragit
CC: Subscribed
Subject: [sunfounder/SunFounder_Dragit] Can't start Dragit on PiCarV V2 (#3)
I'm using the PiCarV V2 with RaspberryPi 1B+, getting this issue:
pi@raspberrypi:/opt/SunFounder_Dragit/Dragit $ sudo ./start
Server running
Performing system checks...
DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
Init GPIO17 success
Init GPIO18 success
Init GPIO27 success
Init GPIO22 success
Init GPIO23 success
Init GPIO24 success
Init GPIO25 success
Init GPIO4 success
Init GPIO5 success
Init GPIO6 success
Init GPIO13 success
Init GPIO19 success
Init GPIO26 success
Init GPIO12 success
Init GPIO16 success
Init GPIO20 success
Init GPIO21 success
DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
No module named pismart.pismart
Unhandled exception in thread started by <function wrapper at 0xb5dbdab0>
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
fn(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 124, in inner_run
self.check(display_num_errors=True)
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
include_deployment_checks=include_deployment_checks,
File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
return checks.run_checks(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
new_errors = check(app_configs=app_configs)
File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
return check_resolver(resolver)
File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
return check_method()
File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 256, in check
for pattern in self.url_patterns:
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in get
res = instance.dict[self.name] = self.func(instance)
File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/lib/python2.7/importlib/init.py", line 37, in import_module
import(name)
File "/opt/SunFounder_Dragit/Dragit/Dragit/urls.py", line 22, in 
from modules import views as modules_views
File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 25, in 
from Dragit.libs.modules.rpi_time import DS1302 as DS1302
File "/opt/SunFounder_Dragit/Dragit/Dragit/libs/modules/rpi_time.py", line 3, in 
import ds1302
ImportError: libwiringPi.so: cannot open shared object file: No such file or directory
What is wrong?
Best Regards

**Comment by MrRSquared** [comment]
Hello,
I am having the same problem.  I tried the workaround and though` sudo service dragit restart` seems to work,

I still cannot find the server from a browser (I am using Chrome).

If I do `sudo ./Dragit/Start/
I get the following readout.

'
Server running
Performing system checks...

DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
Init GPIO17 success
Init GPIO18 success
Init GPIO27 success
Init GPIO22 success
Init GPIO23 success
Init GPIO24 success
Init GPIO25 success
Init GPIO4 success
Init GPIO5 success
Init GPIO6 success
Init GPIO13 success
Init GPIO19 success
Init GPIO26 success
Init GPIO12 success
Init GPIO16 success
Init GPIO20 success
Init GPIO21 success
DEBUG "front_wheels.py": Set debug off
DEBUG "front_wheels.py": Set wheel debug off
DEBUG "Servo.py": Set debug off
DEBUG "back_wheels.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "TB6612.py": Set debug off
DEBUG "PCA9685.py": Set debug off
No module named pismart.pismart
Unhandled exception in thread started by <function wrapper at 0x75aba7f0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line                                                                                                              228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/r                                                                                                             unserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py",                                                                                                              line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py",                                                                                                              line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py",                                                                                                              line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line                                                                                                              16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line                                                                                                              26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 2                                                                                                             56, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line                                                                                                              35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 4                                                                                                             07, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line                                                                                                              35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 4                                                                                                             00, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/SunFounder_Dragit/Dragit/Dragit/urls.py", line 22, in <module>
    from modules import views as modules_views
  File "/opt/SunFounder_Dragit/Dragit/Dragit/modules/views.py", line 25, in <mod                                                                                                             ule>
    from Dragit.libs.modules.rpi_time import DS1302 as DS1302
  File "/opt/SunFounder_Dragit/Dragit/Dragit/libs/modules/rpi_time.py", line 3,                                                                                                              in <module>
    import ds1302
ImportError: libwiringPi.so: cannot open shared object file: No such file or dir                                                                                                             ectory
`
I received a similar error to this before I had the SMBUS working correctly, but now I do.  I can drive the car with Python code just fine.  However, we need dragit to work.  It is the reason we purchased the car.

We have a raspberry Pi 4 as well, and when we try to use it, we get the same error as...
[https://github.com/sunfounder/SunFounder_Dragit/issues/6](https://github.com/sunfounder/SunFounder_Dragit/issues/6)


Any help would be welcome.
~Mr. R^2

**Comment by MrRSquared** [comment]
Hello again,
I emailed Sunfounder support, and they solved my issue.
I used a headless install, and it did not add Wire automatically.

`git clone --recursive https://github.com/neuralpi/WiringPi-Python.git
cd WiringPi-Python/WiringPi
sudo ./build`

Solved it.
